update
reset xyfit_fitpanel back one update in order to avoid error for time
being:
Traceback (most recent call last):
File
"C:\Users\xas_user\AppData\Local\Continuum\Anaconda2\Scripts\gse_mapviewer-script.py",
line 12
from larch_plugins.wx import MapViewer
File
"C:\Users\xas_user\AppData\Local\Continuum\Anaconda2\share\larch\plugins\wx\__init__.py",
line
from .xyfit import XYFitViewer
File
"C:\Users\xas_user\AppData\Local\Continuum\Anaconda2\share\larch\plugins\wx\xyfit.py",
line 44
from larch_plugins.wx.xyfit_fitpanel import XYFitPanel
File
"C:\Users\xas_user\AppData\Local\Continuum\Anaconda2\share\larch\plugins\wx\xyfit_fitpanel.py"
from lmfit.model import save_modelresult, load_modelresult
ImportError: cannot import name save_modelresult